/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yoon.til;

public class App {

  class M extends Thread {
    public M(String name) {
      super(name);
    }
    @Override
    public void run() {
      System.out.println("하나");
    }
  }
  public static void main(String[] args) {
  }
}
